### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by bloodbare** [plone/plone.app.mosaic#8]
TODO

- [ ] Performance tests [ramon]
* Medium mosaic : 552 - 180
* Medium 4.3 : 215 - 70
* Medium 5.0 : 374 - 140
  Numbers : multiadapter vs subrequest / viewletmanager / portletmanager payload /x tile performance
- [ ] Editor UX and finishing
- [ ] Default content layout and site layout design
- [x] Move editor configuration from p.a.blocks:registry.xml into p.a.mosaic
- [x] Fix to work on Plone 5 [datakurre]
- [ ] Saving layout triggers “Are you sure?” [simahawk] [maybe p.a.widgets' issue?]
- [ ] Having multiple editable field tiles (e.g. title) messes up the content during save (could be because they are app tiles) [simahawk]
- [x] Remove tinymce and overlay* from plone.app.mosaic in mosaic [rob]
- [ ] JS tests on plone.app.mosaic [rob]
- [ ] Remove the toolbar styling to the tinymce 4 [rob]
- [ ] The text field of the content doesn’t get stored and rendered and editable [ramon]
- [ ] Fix portlet tile [simahawk]
- [x] Make CMFPlone acceptance tests pass [datakurre]
- [x] Configure Travis-CI with screenshotted sphinx-build to S3 [datakurre]
- [x] Login works only on the second attempt (Plone 4; CMFFormController related) [datakurre]
- [x] Make Blocks transform opt-in instead of opt-out? [datakurre]
https://github.com/plone/plone.app.blocks/issues/11
- [ ] Check versioning compatibility
- [ ] Check working copy compatibility
- [x] Fallback to main template (with data-panel=”content”) when no site layout [datakurre]
- [x] Fix lxml to not produce additional artifacts (like double xmlns:...) [datakurre]
- [x] Fix lxml not quote inline javascripts on some legacy views [datakurre]
- [x] Blocks + Diazo -integration [datakurre]
- [ ] Fix adding tiles to empy blocks (no drop area if you remove all) [rob]
- [ ] Add data-grid -support for Mosaic Editor

**Comment by datakurre** [comment]
Closing this. Let's file separate issues when needed.
